sudo: false
language: c
install:
  - wget --content-disposition https://download.sublimetext.com/latest/dev/linux/x64/syntax_tests
  - tar xf "$(ls st3_syntax_tests_build_*_x64.tar.bz2)"
  - mv st3_syntax_tests/syntax_tests ./
  - rm -R st3_syntax_tests*
before_script:
  - mkdir -p Data/Packages/DotNetConfig/
  - find . -mindepth 1 -maxdepth 1 -not -name 'Data' -not -name 'syntax_tests' -exec mv '{}' Data/Packages/DotNetConfig/ \;
  - wget -O Packages.zip https://github.com/sublimehq/Packages/archive/master.zip
  - unzip Packages.zip
  - find Packages-master/ -mindepth 1 -maxdepth 1 -d -exec mv '{}' Data/Packages/ \;
  - rmdir -r Packages-master
  - rm Packages.zip
  - wget -O xpath.zip https://github.com/rosshadden/sublime-xpath/archive/master.zip
  - unzip xpath.zip
  - mkdir Data/Packages/xpath
  - find xpath-master/ -mindepth 1 -maxdepth 1 -d -exec mv '{}' Data/Packages/xpath/ \;
  - rmdir -r xpath-master
  - rm xpath.zip
script:
- ./syntax_tests
