sudo: false
language: csharp
mono: none
dotnet: 2.1.4 # TODO: see if we can use `latest` here, otherwise version is taken from https://github.com/dotnet/cli/releases

# this section of code taken from https://github.com/randy3k/UnitTesting-example/blob/0e6afad55fa7994666eaa49902747ec7cf29d915/.travis.yml
env:
    global:
        - PACKAGE="SublimeDotNetConfig" # Package name
        - SUBLIME_TEXT_VERSION="3"
# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.3
before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi
# end section
install:
  # these syntax test runner instructions were taken from https://github.com/sublimehq/Packages/blob/cab9faaf1abfcb719d48c1f737641bc1b0f9d3f6/.travis.yml
  - wget --content-disposition https://download.sublimetext.com/latest/dev/linux/x64/syntax_tests
  - tar xf "$(ls st3_syntax_tests_build_*_x64.tar.bz2)"
  - mv st3_syntax_tests/syntax_tests ./
  - rm -R st3_syntax_tests*
  # bootstrap the testing environment - taken from https://github.com/randy3k/UnitTesting-example/blob/0e6afad55fa7994666eaa49902747ec7cf29d915/.travis.yml
  - sh travis.sh bootstrap
  # these instructions were taken from build.py
  - mkdir xdt-transform
  - cd xdt-transform
  - dotnet new web
  # this one is modified from build.py using https://docs.travis-ci.com/user/languages/csharp/
  - nuget install Microsoft.DotNet.Xdt.Tools
before_script:
  - mkdir -p Data/Packages/DotNetConfig/
  - find . -mindepth 1 -maxdepth 1 -not -name 'Data' -not -name 'syntax_tests' -exec mv '{}' Data/Packages/DotNetConfig/ \;
  - wget -O Packages.zip https://github.com/sublimehq/Packages/archive/master.zip
  - unzip Packages.zip
  - find Packages-master/ -mindepth 1 -maxdepth 1 -type d -exec mv '{}' Data/Packages/ \;
  - rm -r Packages-master
  - rm Packages.zip
  - wget -O xpath.zip https://github.com/rosshadden/sublime-xpath/archive/master.zip
  - unzip xpath.zip
  - mkdir Data/Packages/xpath
  - find sublime-xpath-master/ -mindepth 1 -maxdepth 1 -exec mv '{}' Data/Packages/xpath/ \;
  - rm -r sublime-xpath-master
  - rm xpath.zip
script:
  - ./syntax_tests
  # run the unit tests
  - sh travis.sh run_tests --coverage
  # testing syntax_test files
  # - sh travis.sh run_syntax_tests
